import'dotenv/config';import express from'express';import cors from'cors';import helmet from'helmet';import rateLimit from'express-rate-limit';import bcrypt from'bcryptjs';import multer from'multer';import QRCode from'qrcode';import path from'path';import{fileURLToPath}from'url';
import{User,Project,Work,Message,Notification,Content,SupportTicket,PaymentTransaction,PaymentConfig,db}from'./models.js';import{auth,roles,tokenFor,safeUser}from'./auth.js';
import{v2 as cloudinary}from'cloudinary';
import{canStartPayment,commissionFor,paymentSplit}from'./domain.js';
if(!process.env.JWT_SECRET)throw new Error('JWT_SECRET is required');
const app=express(),origin=process.env.CLIENT_URL||'http://localhost:5173';const io={to:()=>({emit:()=>{}}),use:()=>{},on:()=>{}};
if(process.env.CLOUDINARY_CLOUD_NAME)cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
app.use(helmet({crossOriginResourcePolicy:false}));app.use(cors({origin,credentials:true}));app.use('/api/auth',rateLimit({windowMs:15*60*1000,limit:100}));
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:1024*1024*100,files:10},fileFilter:(req,file,cb)=>cb(null,/video|image|zip|octet-stream/.test(file.mimetype))});
const proofUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1},fileFilter:(req,file,cb)=>cb(null,['image/png','image/jpeg','image/webp'].includes(file.mimetype))});
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);const notify=async(user,text,type='system',link='')=>{const n=await Notification.create({user,text,type,link});io.to(`user:${user}`).emit('notification',n)};const getPaymentConfig=()=>PaymentConfig.findOneAndUpdate({key:'default'},{$setOnInsert:{upiId:'earnaster@okicici',payeeName:'FrameBridge'}},{upsert:true,new:true});const upiUri=(config,{amount,note})=>`upi://pay?pa=${encodeURIComponent(config.upiId)}&pn=${encodeURIComponent(config.payeeName)}&am=${Number(amount).toFixed(2)}&cu=INR&tn=${encodeURIComponent(note)}`;
const fileBucket='project-files';let bucketReady;const ensureFileBucket=()=>bucketReady??=(async()=>{const{data}=await db.storage.getBucket(fileBucket);if(data)return;const{error}=await db.storage.createBucket(fileBucket,{public:false,fileSizeLimit:104857600,allowedMimeTypes:['video/*','image/*','application/zip','application/octet-stream']});if(error&&!/already exists/i.test(error.message))throw error})();const storeProjectFile=async(f,userId,kind='source')=>{if(process.env.CLOUDINARY_CLOUD_NAME){const data=`data:${f.mimetype};base64,${f.buffer.toString('base64')}`,saved=await cloudinary.uploader.upload(data,{resource_type:'auto',folder:'framebridge/projects'});return{name:f.originalname,url:saved.secure_url,kind,mime:f.mimetype,size:f.size}}await ensureFileBucket();const safe=f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'),storagePath=`${userId}/${crypto.randomUUID()}-${safe}`;const{error}=await db.storage.from(fileBucket).upload(storagePath,f.buffer,{contentType:f.mimetype,upsert:false});if(error)throw error;return{name:f.originalname,storagePath,kind,mime:f.mimetype,size:f.size}};

app.get('/api/health',(req,res)=>res.json({ok:true,name:'FrameBridge API'}));
app.post('/api/auth/register',asyncRoute(async(req,res)=>{const{role='client',name,email,password,contact,skills=[],experience='',portfolioLinks=[]}=req.body;if(!['client','editor'].includes(role))return res.status(400).json({error:'Invalid role'});if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Name, email and an 8+ character password are required'});if(await User.exists({email:email.toLowerCase()}))return res.status(409).json({error:'Email already registered'});const user=await User.create({role,name,email,password:await bcrypt.hash(password,12),contact,skills,experience,portfolioLinks,status:role==='editor'?'pending':'approved'});res.status(201).json({token:tokenFor(user),user:safeUser(user)})}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const user=await User.findOne({email:req.body.email?.toLowerCase()}).select('+password');if(!user||!await bcrypt.compare(req.body.password||'',user.password))return res.status(401).json({error:'Invalid credentials'});if(user.status==='blocked')return res.status(403).json({error:'Account blocked'});user.lastSeen=new Date();await user.save();res.json({token:tokenFor(user),user:safeUser(user)})}));
app.get('/api/auth/me',auth,(req,res)=>res.json({user:safeUser(req.user)}));

app.get('/api/showcase',asyncRoute(async(req,res)=>{const q={status:'approved'};if(req.query.category)q.category=req.query.category;res.json(await Work.find(q).select('-editor -moderationNote').sort('-approvedAt').lean())}));
app.get('/api/content/:key',asyncRoute(async(req,res)=>res.json((await Content.findOne({key:req.params.key}))?.value??null)));
app.post('/api/projects',auth,roles('client'),upload.array('files',10),asyncRoute(async(req,res)=>{const budget=Number(req.body.budget);if(!req.body.title?.trim()||!req.body.category?.trim()||!Number.isFinite(budget)||budget<1)return res.status(400).json({error:'Title, category, and a valid budget are required'});const files=await Promise.all((req.files||[]).map(async f=>{if(!process.env.CLOUDINARY_CLOUD_NAME)return{name:f.originalname,url:`pending-storage://${f.originalname}`,kind:'source'};const data=`data:${f.mimetype};base64,${f.buffer.toString('base64')}`,saved=await cloudinary.uploader.upload(data,{resource_type:'auto',folder:'framebridge/projects'});return{name:f.originalname,url:saved.secure_url,kind:'source'}}));const p=await Project.create({client:req.user._id,title:req.body.title.trim(),category:req.body.category.trim(),brief:req.body.brief,deadline:req.body.deadline||undefined,budget,files,status:'matching'});await notify(req.user._id,`Project “${p.title}” was submitted`,'project',`/projects/${p._id}`);res.status(201).json(p)}));
app.get('/api/projects',auth,asyncRoute(async(req,res)=>{const q=req.user.role==='client'?{client:req.user._id}:req.user.role==='editor'?{editor:req.user._id}:{};res.json(await Project.find(q).populate('client editor','name email').sort('-createdAt'))}));
app.get('/api/projects/:id',auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id).populate('client editor','name email');if(!p)return res.status(404).json({error:'Not found'});if(req.user.role!=='admin'&&!p.client._id.equals(req.user._id)&&!(p.editor&&p.editor._id.equals(req.user._id)))return res.status(403).json({error:'Forbidden'});res.json(p)}));
app.post('/api/projects/:id/files',auth,upload.array('files',10),asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({error:'Project not found'});const allowed=req.user.role==='admin'||p.client.equals(req.user._id)||p.editor?.equals(req.user._id);if(!allowed)return res.status(403).json({error:'Forbidden'});if(!req.files?.length)return res.status(400).json({error:'Choose at least one supported file'});const kind=req.user.role==='editor'?'delivery':'source',files=await Promise.all(req.files.map(f=>storeProjectFile(f,req.user._id,kind)));p.files=[...(p.files||[]),...files];await p.save();res.status(201).json({files:p.files})}));
app.get('/api/projects/:id/files/:index',auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({error:'Project not found'});const allowed=req.user.role==='admin'||p.client.equals(req.user._id)||p.editor?.equals(req.user._id);if(!allowed)return res.status(403).json({error:'Forbidden'});const file=p.files?.[Number(req.params.index)];if(!file)return res.status(404).json({error:'File not found'});if(file.storagePath){const{data,error}=await db.storage.from(fileBucket).download(file.storagePath);if(error)throw error;res.type(file.mime||'application/octet-stream');res.setHeader('Content-Disposition',`attachment; filename="${String(file.name).replace(/["\r\n]/g,'_')}"`);return res.send(Buffer.from(await data.arrayBuffer()))}if(file.url?.startsWith('http'))return res.redirect(file.url);res.status(410).json({error:'This older file was not stored. Please upload it again.'})}));
app.patch('/api/projects/:id/quote',auth,roles('editor','admin'),asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({error:'Project not found'});if(req.user.role==='editor'&&!p.editor?.equals(req.user._id))return res.status(403).json({error:'Forbidden'});const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<1)return res.status(400).json({error:'A valid quote amount is required'});p.quote={amount,deadline:req.body.deadline,message:req.body.message};p.status='quoted';await p.save();await notify(p.client,'A quote is ready for your project','quote',`/projects/${p._id}`);res.json(p)}));
app.patch('/api/projects/:id/accept',auth,roles('client'),asyncRoute(async(req,res)=>{const p=await Project.findOne({_id:req.params.id,client:req.user._id});if(!p||p.status!=='quoted')return res.status(400).json({error:'Quote unavailable'});p.quote.acceptedAt=new Date();const split=paymentSplit(p.quote.amount);p.payment.advance=split.advance;p.payment.balance=split.balance;p.payment.status='pending_payment';p.status='awaiting_advance';await p.save();res.json(p)}));
app.patch('/api/projects/:id/progress',auth,roles('editor','admin'),asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({error:'Not found'});if(req.user.role==='editor'&&!p.editor?.equals(req.user._id))return res.status(403).json({error:'Forbidden'});p.progress=Math.max(0,Math.min(100,Number(req.body.progress)));p.status=p.progress===100?'review':'in_progress';await p.save();await notify(p.client,`${p.title} is now ${p.progress}% complete`,'progress',`/projects/${p._id}`);io.to(`project:${p._id}`).emit('project:update',p);res.json(p)}));
app.patch('/api/projects/:id/complete',auth,roles('admin'),asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p||!p.editor||p.status==='completed')return res.status(400).json({error:'Project cannot be completed'});if(!p.payment.balancePaid)return res.status(409).json({error:'Balance must be paid first'});const editor=await User.findById(p.editor);p.commission=commissionFor(p.quote.amount,editor.completedProjects);p.status='completed';p.progress=100;p.completedAt=new Date();editor.completedProjects+=1;await Promise.all([p.save(),editor.save()]);res.json(p)}));
app.patch('/api/projects/:id/approve',auth,roles('client'),asyncRoute(async(req,res)=>{const p=await Project.findOne({_id:req.params.id,client:req.user._id,status:'awaiting_balance'});if(!p||!p.editor)return res.status(400).json({error:'Project is not ready for approval'});if(!p.payment.balancePaid)return res.status(409).json({error:'Final balance must be paid first'});const editor=await User.findById(p.editor);p.commission=commissionFor(p.quote.amount,editor.completedProjects);p.status='completed';p.progress=100;p.completedAt=new Date();editor.completedProjects+=1;await Promise.all([p.save(),editor.save()]);await notify(editor._id,`${p.title} was approved and completed`,'completion',`/projects/${p._id}`);res.json(p)}));

app.get('/api/payments/config',auth,asyncRoute(async(req,res)=>{const config=await getPaymentConfig();res.json({upiId:config.upiId,payeeName:config.payeeName,qrUrl:'/api/payments/qr'})}));
app.get('/api/payments/qr',asyncRoute(async(req,res)=>{const config=await PaymentConfig.findOneAndUpdate({key:'default'},{$setOnInsert:{upiId:'earnaster@okicici',payeeName:'FrameBridge'}},{upsert:true,new:true}).select('+qrImageData');if(config.qrImageData){res.type(config.qrImageMime||'image/png');return res.send(config.qrImageData)}const amount=Math.max(0,Number(req.query.amount)||0),note=String(req.query.note||'FrameBridge payment').slice(0,80);const png=await QRCode.toBuffer(upiUri(config,{amount,note}),{type:'png',width:420,margin:2,errorCorrectionLevel:'M'});res.type('image/png').send(png)}));
app.post('/api/payments/:projectId/create-intent',auth,roles('client'),asyncRoute(async(req,res)=>{const p=await Project.findOne({_id:req.params.projectId,client:req.user._id});if(!p)return res.status(404).json({error:'Project not found'});const stage=req.body.stage==='balance'?'balance':'advance';if(!canStartPayment(p,stage))return res.status(409).json({error:`${stage==='advance'?'Advance payment':'Final balance'} is not currently due or is already under review`});const amount=p.payment[stage],config=await getPaymentConfig(),note=`FrameBridge ${stage} ${p._id}`;res.json({projectId:p._id,projectTitle:p.title,amount,stage,upiId:config.upiId,payeeName:config.payeeName,upiUri:upiUri(config,{amount,note}),qrUrl:`/api/payments/qr?amount=${encodeURIComponent(amount)}&note=${encodeURIComponent(note)}`})}));
app.post('/api/payments/:projectId/submit',auth,roles('client'),proofUpload.single('proof'),asyncRoute(async(req,res)=>{const p=await Project.findOne({_id:req.params.projectId,client:req.user._id});if(!p)return res.status(404).json({error:'Project not found'});const stage=req.body.stage==='balance'?'balance':'advance';if(!canStartPayment(p,stage))return res.status(409).json({error:'This payment is not currently due or was already submitted'});if(!req.file)return res.status(400).json({error:'A PNG, JPG, or WebP payment screenshot is required'});const transactionId=String(req.body.transactionId||'').trim().toUpperCase(),paidAt=new Date(req.body.paidAt);if(!/^[A-Z0-9-]{6,50}$/.test(transactionId)||Number.isNaN(paidAt.getTime()))return res.status(400).json({error:'A valid transaction ID and payment date/time are required'});const config=await getPaymentConfig(),tx=await PaymentTransaction.create({project:p._id,client:req.user._id,stage,amount:p.payment[stage],upiId:config.upiId,transactionId,paidAt,status:'under_verification',proofData:req.file.buffer,proofMime:req.file.mimetype});p.payment.status='under_verification';await p.save();await notify(req.user._id,'Payment proof submitted and awaiting admin verification','payment',`/projects/${p._id}`);res.status(201).json({id:tx._id,status:tx.status,amount:tx.amount})}));
app.get('/api/payments/:projectId/history',auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.projectId);if(!p||req.user.role!=='admin'&&!p.client.equals(req.user._id)&&!p.editor?.equals(req.user._id))return res.status(403).json({error:'Forbidden'});res.json(await PaymentTransaction.find({project:p._id}).select('-proofData').sort('-createdAt'))}));

app.get('/api/projects/:id/messages',auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p||req.user.role!=='admin'&&!p.client.equals(req.user._id)&&!p.editor?.equals(req.user._id))return res.status(403).json({error:'Forbidden'});res.json(await Message.find({project:req.params.id}).populate('sender','name role').sort('createdAt'))}));
app.post('/api/projects/:id/messages',auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({error:'Not found'});const isClient=req.user._id.equals(p.client),isEditor=p.editor?.equals(req.user._id);if(req.user.role!=='admin'&&!isClient&&!isEditor)return res.status(403).json({error:'Forbidden'});const recipient=isClient?p.editor:p.client;if(!recipient)return res.status(400).json({error:'No recipient assigned'});const m=await Message.create({project:p._id,sender:req.user._id,recipient,body:req.body.body});await notify(recipient,`New message about ${p.title}`,'message',`/projects/${p._id}`);io.to(`project:${p._id}`).emit('message',await m.populate('sender','name role'));res.status(201).json(m)}));
app.get('/api/notifications',auth,asyncRoute(async(req,res)=>res.json(await Notification.find({user:req.user._id}).sort('-createdAt').limit(50))));app.patch('/api/notifications/read',auth,asyncRoute(async(req,res)=>{await Notification.updateMany({user:req.user._id,readAt:null},{readAt:new Date()});res.json({ok:true})}));

app.post('/api/editor/works',auth,roles('editor'),asyncRoute(async(req,res)=>{if(!req.body.title?.trim()||!req.body.category?.trim())return res.status(400).json({error:'Title and category are required'});try{const url=new URL(req.body.videoUrl);if(!['http:','https:'].includes(url.protocol))throw new Error()}catch{return res.status(400).json({error:'A valid public video URL is required'})}res.status(201).json(await Work.create({...req.body,title:req.body.title.trim(),category:req.body.category.trim(),editor:req.user._id,status:'pending'}))}));
app.get('/api/editor/requests',auth,roles('editor'),asyncRoute(async(req,res)=>res.json(await Project.find({editor:null,status:'matching'}).select('title category brief deadline budget createdAt').sort('-createdAt').limit(30))));
app.get('/api/editor/stats',auth,roles('editor'),asyncRoute(async(req,res)=>{const projects=await Project.find({editor:req.user._id});const completed=projects.filter(p=>p.status==='completed'),gross=completed.reduce((sum,p)=>sum+(p.quote?.amount||0),0),commission=completed.reduce((sum,p)=>sum+(p.commission?.amount||0),0);res.json({completedProjects:req.user.completedProjects,currentProjects:projects.filter(p=>!['completed','cancelled'].includes(p.status)).length,commissionRate:req.user.completedProjects<4?.17:.10,grossEarnings:gross,commissionPaid:commission,netEarnings:gross-commission})}));
app.post('/api/support',rateLimit({windowMs:60*60*1000,limit:10}),asyncRoute(async(req,res)=>{const ticket=await SupportTicket.create(req.body);res.status(201).json({id:ticket._id,message:'Support request received'})}));
app.get('/api/admin/stats',auth,roles('admin'),asyncRoute(async(req,res)=>{const[users,projects,pendingWorks,pendingPayments,revenue]=await Promise.all([User.countDocuments(),Project.countDocuments(),Work.countDocuments({status:'pending'}),PaymentTransaction.countDocuments({status:'under_verification'}),Project.aggregate([{$match:{status:'completed'}},{$group:{_id:null,total:{$sum:'$commission.amount'}}}])]);res.json({users,projects,pendingWorks,pendingPayments,platformRevenue:revenue[0]?.total||0})}));
app.get('/api/admin/users',auth,roles('admin'),asyncRoute(async(req,res)=>res.json(await User.find().sort('-createdAt'))));
app.get('/api/admin/projects',auth,roles('admin'),asyncRoute(async(req,res)=>res.json(await Project.find().populate('client editor','name email').sort('-createdAt'))));
app.get('/api/admin/works',auth,roles('admin'),asyncRoute(async(req,res)=>res.json(await Work.find().populate('editor','name email').sort('-createdAt'))));
app.get('/api/admin/payments',auth,roles('admin'),asyncRoute(async(req,res)=>res.json(await PaymentTransaction.find().select('-proofData').populate('client','name email').populate('project','title status').populate('verifiedBy','name email').sort('-createdAt'))));
app.get('/api/admin/payments/config',auth,roles('admin'),asyncRoute(async(req,res)=>{const config=await getPaymentConfig();res.json({upiId:config.upiId,payeeName:config.payeeName,qrUrl:'/api/payments/qr'})}));
app.put('/api/admin/payments/config',auth,roles('admin'),proofUpload.single('qrImage'),asyncRoute(async(req,res)=>{const upiId=String(req.body.upiId||'').trim(),payeeName=String(req.body.payeeName||'FrameBridge').trim();if(!/^[\w.-]{2,}@[\w.-]{2,}$/.test(upiId))return res.status(400).json({error:'A valid UPI ID is required'});const update={upiId,payeeName,updatedBy:req.user._id};if(req.file){update.qrImageData=req.file.buffer;update.qrImageMime=req.file.mimetype}const config=await PaymentConfig.findOneAndUpdate({key:'default'},update,{upsert:true,new:true});res.json({upiId:config.upiId,payeeName:config.payeeName,qrUrl:'/api/payments/qr'})}));
app.get('/api/admin/payments/:id/proof',auth,roles('admin'),asyncRoute(async(req,res)=>{const tx=await PaymentTransaction.findById(req.params.id).select('+proofData');if(!tx)return res.status(404).json({error:'Transaction not found'});res.type(tx.proofMime).send(tx.proofData)}));
app.patch('/api/admin/payments/:id/verify',auth,roles('admin'),asyncRoute(async(req,res)=>{const tx=await PaymentTransaction.findById(req.params.id),action=req.body.action;if(!tx)return res.status(404).json({error:'Transaction not found'});const p=await Project.findById(tx.project);if(!p)return res.status(404).json({error:'Project not found'});if(action==='refund'){if(tx.status!=='payment_approved'||p.status==='completed')return res.status(409).json({error:'This transaction cannot be refunded here'});tx.status='refunded';tx.refundNote=String(req.body.reason||'Manual refund');tx.refundedAt=new Date();p.payment[tx.stage==='advance'?'advancePaid':'balancePaid']=false;p.payment.status='payment_rejected';p.status=tx.stage==='advance'?'awaiting_advance':'review';await Promise.all([tx.save(),p.save()]);return res.json(tx)}if(tx.status!=='under_verification')return res.status(409).json({error:'Transaction was already reviewed'});tx.verifiedBy=req.user._id;tx.verifiedAt=new Date();if(action==='approve'){if(Number(tx.amount)!==Number(p.payment[tx.stage]))return res.status(409).json({error:'Submitted amount does not match the amount due'});tx.status='payment_approved';p.payment[tx.stage==='advance'?'advancePaid':'balancePaid']=true;if(tx.stage==='advance'){p.payment.status='remaining_payment_pending';p.status='in_progress';if(p.editor)await notify(p.editor,'Advance payment verified. Editing can begin.','payment',`/projects/${p._id}`)}else{p.payment.status='completed';p.status='awaiting_balance';if(p.editor)await notify(p.editor,'Final payment verified. The client can approve the project.','payment',`/projects/${p._id}`)}await notify(p.client,'Your payment was verified by the manager.','payment',`/projects/${p._id}`)}else if(action==='reject'){tx.status='payment_rejected';tx.rejectionReason=String(req.body.reason||'Payment proof could not be verified');p.payment.status='payment_rejected';p.status=tx.stage==='advance'?'awaiting_advance':'review';await notify(p.client,`Payment rejected: ${tx.rejectionReason}`,'payment',`/projects/${p._id}`)}else return res.status(400).json({error:'Action must be approve, reject, or refund'});await Promise.all([tx.save(),p.save()]);res.json(tx)}));
app.get('/api/admin/support',auth,roles('admin'),asyncRoute(async(req,res)=>res.json(await SupportTicket.find().sort('-createdAt'))));
app.patch('/api/admin/support/:id',auth,roles('admin'),asyncRoute(async(req,res)=>res.json(await SupportTicket.findByIdAndUpdate(req.params.id,{status:req.body.status,assignedTo:req.user._id},{new:true}))));
app.patch('/api/admin/users/:id',auth,roles('admin'),asyncRoute(async(req,res)=>{const allowed=['status','name','contact','skills','experience'];const changes=Object.fromEntries(Object.entries(req.body).filter(([k])=>allowed.includes(k)));res.json(await User.findByIdAndUpdate(req.params.id,changes,{new:true}))}));
app.patch('/api/admin/projects/:id/assign',auth,roles('admin'),asyncRoute(async(req,res)=>{const editor=await User.findOne({_id:req.body.editorId,role:'editor',status:'approved'});if(!editor)return res.status(400).json({error:'Approved editor required'});const p=await Project.findByIdAndUpdate(req.params.id,{editor:editor._id,status:'assigned'},{new:true});if(!p)return res.status(404).json({error:'Project not found'});await notify(editor._id,`You were assigned to ${p.title}`,'assignment',`/projects/${p._id}`);res.json(p)}));
app.patch('/api/admin/works/:id',auth,roles('admin'),asyncRoute(async(req,res)=>{const status=req.body.status;const w=await Work.findByIdAndUpdate(req.params.id,{status,moderationNote:req.body.moderationNote,approvedAt:status==='approved'?new Date():undefined},{new:true});await notify(w.editor,`Your showcase submission was ${status}`,'moderation');res.json(w)}));
app.put('/api/admin/content/:key',auth,roles('admin'),asyncRoute(async(req,res)=>res.json(await Content.findOneAndUpdate({key:req.params.key},{value:req.body.value},{upsert:true,new:true}))));


const root=path.dirname(fileURLToPath(import.meta.url));if(process.env.NODE_ENV==='production'){app.use(express.static(path.join(root,'../dist')));app.get('{*splat}',(req,res)=>res.sendFile(path.join(root,'../dist/index.html')))}
app.use((err,req,res,next)=>{console.error(err);res.status(err.code===11000?409:500).json({error:err.code===11000?'Already exists':'Server error'})});export default app;
