import mongoose from 'mongoose';
const {Schema,model}=mongoose;

const userSchema=new Schema({
 role:{type:String,enum:['client','editor','admin'],default:'client',index:true},name:{type:String,required:true,trim:true},email:{type:String,required:true,unique:true,lowercase:true,index:true},password:{type:String,required:true,select:false},contact:String,status:{type:String,enum:['pending','approved','blocked'],default:'approved'},skills:[String],experience:String,completedProjects:{type:Number,default:0},portfolioLinks:[String],lastSeen:Date
},{timestamps:true});
userSchema.methods.public=function(){const o=this.toObject();delete o.password;return o};

const projectSchema=new Schema({
 client:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},editor:{type:Schema.Types.ObjectId,ref:'User',index:true},title:{type:String,required:true,trim:true,maxlength:160},category:{type:String,required:true,trim:true},brief:{type:String,maxlength:10000},deadline:Date,budget:{type:Number,min:1,required:true},status:{type:String,enum:['submitted','matching','assigned','quoted','awaiting_advance','in_progress','review','awaiting_balance','completed','cancelled'],default:'submitted',index:true},progress:{type:Number,min:0,max:100,default:0},files:[{name:String,url:String,kind:{type:String,default:'source'}}],quote:{amount:Number,deadline:Date,message:String,acceptedAt:Date},payment:{advance:{type:Number,default:0},balance:{type:Number,default:0},advancePaid:{type:Boolean,default:false},balancePaid:{type:Boolean,default:false},status:{type:String,enum:['pending_payment','payment_submitted','under_verification','payment_approved','payment_rejected','remaining_payment_pending','completed'],default:'pending_payment'}},commission:{rate:Number,amount:Number,editorNet:Number},completedAt:Date
},{timestamps:true});

const workSchema=new Schema({editor:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},title:{type:String,required:true},category:{type:String,required:true},videoUrl:{type:String,required:true},thumbnailUrl:String,status:{type:String,enum:['pending','approved','rejected'],default:'pending',index:true},moderationNote:String,approvedAt:Date},{timestamps:true});
const messageSchema=new Schema({project:{type:Schema.Types.ObjectId,ref:'Project',index:true},sender:{type:Schema.Types.ObjectId,ref:'User',required:true},recipient:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},body:{type:String,required:true,maxlength:4000},readAt:Date},{timestamps:true});
const notificationSchema=new Schema({user:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},type:String,text:String,link:String,readAt:Date},{timestamps:true});
const contentSchema=new Schema({key:{type:String,unique:true},value:Schema.Types.Mixed},{timestamps:true});
const supportSchema=new Schema({name:String,email:{type:String,required:true},subject:String,message:{type:String,required:true,maxlength:5000},status:{type:String,enum:['open','in_progress','resolved'],default:'open'},assignedTo:{type:Schema.Types.ObjectId,ref:'User'}},{timestamps:true});
const paymentTransactionSchema=new Schema({project:{type:Schema.Types.ObjectId,ref:'Project',required:true,index:true},client:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},stage:{type:String,enum:['advance','balance'],required:true},amount:{type:Number,required:true,min:1},upiId:{type:String,required:true},transactionId:{type:String,required:true,trim:true,uppercase:true,index:true},paidAt:{type:Date,required:true},status:{type:String,enum:['payment_submitted','under_verification','payment_approved','payment_rejected','refunded'],default:'under_verification',index:true},proofData:{type:Buffer,required:true,select:false},proofMime:{type:String,required:true},verifiedBy:{type:Schema.Types.ObjectId,ref:'User'},verifiedAt:Date,rejectionReason:String,refundNote:String,refundedAt:Date},{timestamps:true});
paymentTransactionSchema.index({transactionId:1},{unique:true});paymentTransactionSchema.index({project:1,stage:1,status:1});
const paymentConfigSchema=new Schema({key:{type:String,default:'default',unique:true},upiId:{type:String,required:true,default:'earnaster@okicici'},payeeName:{type:String,default:'FrameBridge'},qrImageData:{type:Buffer,select:false},qrImageMime:String,updatedBy:{type:Schema.Types.ObjectId,ref:'User'}},{timestamps:true});

export const User=model('User',userSchema);export const Project=model('Project',projectSchema);export const Work=model('Work',workSchema);export const Message=model('Message',messageSchema);export const Notification=model('Notification',notificationSchema);export const Content=model('Content',contentSchema);export const SupportTicket=model('SupportTicket',supportSchema);export const PaymentTransaction=model('PaymentTransaction',paymentTransactionSchema);export const PaymentConfig=model('PaymentConfig',paymentConfigSchema);
